services:

  ollama:
    image: ollama/ollama
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: ["serve"]
      
  postgres:
    image: postgres:15
    container_name: financial_ocr_postgres
    restart: always
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
      POSTGRES_DB: finance_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: financial_ocr_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build: ./backend
    container_name: financial_ocr_backend
    restart: always
    depends_on:
      - postgres
      - minio
      - ollama
    environment:
      DATABASE_URL: postgresql://finance_user:finance_pass@postgres:5432/finance_db
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      OLLAMA_URL: http://ollama:11434/api/chat
      OLLAMA_LOCAL_URL: http://localhost:11434/api/chat
      OLLAMA_MODEL: scb10x/llama3.1-typhoon2-8b-instruct
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: financial_ocr_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    ports:
      - "3001:3001"

volumes:
  pgdata:
  minio_data:
  ollama_data: